[HRS-18] Create PWA Layout

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,8 @@
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "main" || "$branch" = "develop" ]; then
+  echo "You can't commit directly to main or develop branch"
+  exit 1
+fi
+
 npx lint-staged
